export enum NotificationMethodStatuses {
  NOTIFICATION_STATUS_UNSPECIFIED = 0,
  NOTIFICATION_STATUS_ACTIVE = 1,
  NOTIFICATION_STATUS_INACTIVE = 2,
  NOTIFICATION_STATUS_REMOVED = 3,
}

export enum NotificationMethodType {
  NOTIFICATION_METHOD_UNSPECIFIED = 0,
  NOTIFICATION_METHOD_WEBHOOK = 1,
  NOTIFICATION_METHOD_SLACK = 2,
}
