export enum OwnerType {
  INCIDENT_OWNER_TYPE_UNSPECIFIED = 0,
  INCIDENT_OWNER_TYPE_SCHEDULER = 1,
  INCIDENT_OWNER_TYPE_AGENT = 2,
  INCIDENT_OWNER_TYPE_APPLICATION = 3,
}

export enum RuleStatus {
  RULE_STATUS_UNSPECIFIED = 0,
  RULE_STATUS_ACTIVE = 1,
  RULE_STATUS_INACTIVE = 2,
  RULE_STATUS_REMOVED = 3,
}
